### ISSUE TITLE
Mutable subCounters

### ISSUE THREAD

**Issue by Tavistock** [Chat-Wane/LSEQTree#9]
If the add function on the LSEQ-Node travels down a limb towards an element it currently [increases all the subCounters](https://github.com/Chat-Wane/LSEQTree/blob/master/lib/lseqnode.js#L29) even if it ends up [not adding any more elements](https://github.com/Chat-Wane/LSEQTree/blob/master/lib/lseqnode.js#L40).
I also would like to talk to about some confusion I have about how the lseq crdt works, is there any way I could contact you?

**Comment by Chat-Wane** [comment]
Thank you for the bug report! I will fix that asap ( hopefully at the end of the week).

I'll gladly answer your questions. You can ask them at brice.nedelec@univ-nantes.fr

**Comment by Tavistock** [comment]
here's what i did, modified getIndexes function to return a collection like yours but if it hits a no index instead of returning -1 it returns nil append to the collection. so it would return something like [1 2 0 5 nil]. from here if it is something like [1 2 3 4] it already has a node there so you go to that node and check if it has a element and if it does no-op if it doesn't increase all the sub-counters leading to it then added it. if it is an array ending in a nil you know it is not there so you can crawl to it using the indexes, increasing sub-counters on the way, and add the node into the last indices children.

The only reason I mention this is because i found that a simple modification of getIndexes function increases it's usefulness and wanted to share. I'm not sure if you use the semantic of returning -1 on a not-found in your code but I looked around and couldn't find it.

**Comment by Chat-Wane** [comment]
Ah, indeed.

I was considering a solution where the recursive function returns a boolean on whether or not it actually inserts the new element in the lower branches of the tree. You solution is way much easier to write and to understand, thanks.

Btw, your project looks nice. I was thinking about referencing it in the readme, is that ok with you?

**Comment by Tavistock** [comment]
yea, that would be great. I may write some blog posts about crdt's and focus on sequence ones, if I mention you would your github handle be good or would you prefer something else.

**Comment by Chat-Wane** [comment]
Ok, great, I'll do. You can reference whatever seems the most appropriate to you ;)

**Comment by Chat-Wane** [comment]
I finally fix the issue. Nevertheless, I didn't implemented the way you suggested. I tried, but it actually increased the algorithm complexity... Instead, I just checked if the node was actually added before incrementing the counter (using the returning value of the add function).
